name: "Greenbox MQTT Bridge"
version: "1.0.0"
slug: "greenbox_bridge"
description: "Steuerung der BerlinGreen Greenbox via BLE"
arch:
  - aarch64
  - amd64
  - armv7
startup: "services"
boot: "auto"
full_access: true # Wichtig f√ºr Bluetooth-Hardwarezugriff
host_network: true
host_dbus: true # Erlaubt die Kommunikation mit dem Bluetooth-Dienst des Hosts

options:
  ble_address: "8C:4B:14:84:DB:72"
  mqtt_host: "core-mosquitto"
  mqtt_user: ""
  mqtt_pass: ""
  device_id: "greenbox_berlin"
  device_name: "Greenbox"

schema:
  ble_address: str
  mqtt_host: str
  mqtt_user: str?
  mqtt_pass: str?
  device_id: str
  device_name: str