name: "Greenbox MQTT Bridge"
version: "1.0.7"
slug: "greenbox_bridge"
description: "Steuerung der BerlinGreen Greenbox via BLE"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: "services"
boot: "auto"
host_network: true
# DBus is required for Bleak/Bluetooth
host_dbus: true
# Map /data for persistent storage
map:
  - config:rw
# This allows the container to access Bluetooth hardware
privileged:
  - SYS_ADMIN
  - NET_ADMIN

options:
  ble_address: "8C:4B:14:84:DB:72"
  mqtt_host: "core-mosquitto"
  mqtt_user: ""
  mqtt_pass: ""
  device_id: "greenbox_berlin"
  device_name: "Greenbox"
  debug: false

schema:
  ble_address: str
  mqtt_host: str
  mqtt_user: str?
  mqtt_pass: str?
  device_id: str
  device_name: str
  debug: bool