[project]
name = "greenbox_integration"
version = "0.1.0"
description = "BLE to MQTT Bridge for Greenbox"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=2.1.1",
    "paho-mqtt>=2.1.0",
]
